/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author DAM
 */
public class IDatosTripulacion extends javax.swing.JDialog {

    /**
     * Creates new form IDatosTripulacion
     */
    public IDatosTripulacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void compruNumero(java.awt.event.KeyEvent evt){
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            JOptionPane.showMessageDialog(this, "En este capo solo puedes introducir numeros", "Solo numeros", JOptionPane.ERROR_MESSAGE);
            evt.consume();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fotoDato = new javax.swing.JLabel();
        botonAñadirFT = new javax.swing.JButton();
        botonBorrarFT = new javax.swing.JButton();
        botonAnyadirFT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombreT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellido1T = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellido2T = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dniT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telefonoT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        coElectronicoT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        direccionT = new javax.swing.JTextField();
        botonAceptarT = new javax.swing.JButton();
        botonLimpiarT = new javax.swing.JButton();
        paneinvisible = new javax.swing.JPanel();
        buttonPiloto = new javax.swing.JRadioButton();
        buttonCopiloto = new javax.swing.JRadioButton();
        buttonAzafata = new javax.swing.JRadioButton();
        textoCategoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextoT = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        comboT = new javax.swing.JComboBox();
        textoClase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        edadT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fotoDato.setText("FOTO");

        botonAñadirFT.setText("Añadir");

        botonBorrarFT.setText("Borrar");

        botonAnyadirFT.setText("Cambiar");

        jLabel2.setText("Nombre:");

        nombreT.setText("gabriel");

        jLabel3.setText("Primer apellido:");

        apellido1T.setText("chiriboga");

        jLabel4.setText("Segundo apellido:");

        apellido2T.setText("rogel");

        jLabel5.setText("DNI:");

        dniT.setText("23863977m");

        jLabel6.setText("Telefono:");

        telefonoT.setText("695810083");
        telefonoT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTKeyTyped(evt);
            }
        });

        jLabel7.setText("Correo electronico:");

        coElectronicoT.setText("gabriel@gmail.com");

        jLabel8.setText("Direccion:");

        direccionT.setText("bilbao");

        botonAceptarT.setText("Aceptar");

        botonLimpiarT.setText("Limpiar");

        buttonGroup1.add(buttonPiloto);
        buttonPiloto.setText("Piloto");

        buttonGroup1.add(buttonCopiloto);
        buttonCopiloto.setText("Copiloto");

        buttonGroup1.add(buttonAzafata);
        buttonAzafata.setText("Azafata");

        textoCategoria.setText("Categoria:");

        javax.swing.GroupLayout paneinvisibleLayout = new javax.swing.GroupLayout(paneinvisible);
        paneinvisible.setLayout(paneinvisibleLayout);
        paneinvisibleLayout.setHorizontalGroup(
            paneinvisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneinvisibleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(buttonPiloto)
                .addGap(18, 18, 18)
                .addComponent(buttonCopiloto)
                .addGap(18, 18, 18)
                .addComponent(buttonAzafata)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(paneinvisibleLayout.createSequentialGroup()
                .addComponent(textoCategoria)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneinvisibleLayout.setVerticalGroup(
            paneinvisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneinvisibleLayout.createSequentialGroup()
                .addComponent(textoCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(paneinvisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPiloto)
                    .addComponent(buttonCopiloto)
                    .addComponent(buttonAzafata))
                .addContainerGap())
        );

        areaTextoT.setColumns(20);
        areaTextoT.setRows(5);
        jScrollPane1.setViewportView(areaTextoT);

        jLabel9.setText("Informacion adicional:");

        comboT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primera", "Segunda", "Tercera" }));

        textoClase.setText("Clase:");

        jLabel1.setText("Edad:");

        edadT.setText("25");
        edadT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edadTKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(fotoDato))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreT)
                            .addComponent(apellido1T)
                            .addComponent(apellido2T)
                            .addComponent(dniT)
                            .addComponent(coElectronicoT)
                            .addComponent(direccionT, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(telefonoT, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(edadT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonAnyadirFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonBorrarFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAñadirFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneinvisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textoClase)
                                .addGap(18, 18, 18)
                                .addComponent(comboT, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(botonAceptarT)
                .addGap(18, 18, 18)
                .addComponent(botonLimpiarT)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(paneinvisible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoClase)
                                    .addComponent(comboT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonAñadirFT)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fotoDato)
                                    .addComponent(botonBorrarFT))
                                .addGap(18, 18, 18)
                                .addComponent(botonAnyadirFT)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(apellido1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(apellido2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dniT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(edadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coElectronicoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptarT)
                    .addComponent(botonLimpiarT))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edadTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edadTKeyTyped
        compruNumero(evt);
    }//GEN-LAST:event_edadTKeyTyped

    private void telefonoTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTKeyTyped
        compruNumero(evt);
    }//GEN-LAST:event_telefonoTKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDatosTripulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDatosTripulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDatosTripulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDatosTripulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IDatosTripulacion dialog = new IDatosTripulacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField apellido1T;
    public javax.swing.JTextField apellido2T;
    public javax.swing.JTextArea areaTextoT;
    public javax.swing.JButton botonAceptarT;
    public javax.swing.JButton botonAnyadirFT;
    public javax.swing.JButton botonAñadirFT;
    public javax.swing.JButton botonBorrarFT;
    public javax.swing.JButton botonLimpiarT;
    public javax.swing.JRadioButton buttonAzafata;
    public javax.swing.JRadioButton buttonCopiloto;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JRadioButton buttonPiloto;
    public javax.swing.JTextField coElectronicoT;
    public javax.swing.JComboBox comboT;
    public javax.swing.JTextField direccionT;
    public javax.swing.JTextField dniT;
    public javax.swing.JTextField edadT;
    public javax.swing.JLabel fotoDato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nombreT;
    public javax.swing.JPanel paneinvisible;
    public javax.swing.JTextField telefonoT;
    public javax.swing.JLabel textoCategoria;
    public javax.swing.JLabel textoClase;
    // End of variables declaration//GEN-END:variables
}
